### ISSUE TITLE
Differences between resty and nestjs?

### ISSUE THREAD

**Issue by wxs77577** [restyjs/resty#43]

**Comment by satishbabariya** [comment]
- resty = express + routing-controllers

- resty is **simple** and **less complex** compare to nest.js
- nest.js has **providers, controllers, services, modules, guards, pipes**. in resty we only have **controllers**
- nest.js is built on angular philosophy, resty is not.

- resty is purely based on **express**, so you can use resty on any existing express app or create a new one.
- you can use **any express middleware** in resty out of the box. like: (joi, multer ...)


resty example:
```ts
import resty, { Controller, Get, Context } from "@restyjs/core";

@Controller("/hello")
class HelloController {

  @Get("/")
  index() {
    return "Hello World";
  }
}

const app = resty({
  controllers: [HelloController],
});

app.listen(8080);
```
